name: Ambil data daftar hari libur
on:
  schedule:
    # Jalankan setiap tanggal 1 Januari.
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '>=18'
        cache: 'pnpm'
    - name: Install dependecies
      run: pnpm install --no-frozen-lockfile
    - name: Test puppeter
      run: pnpm run puppet
    - name: Ambil data daftar hari libur
      run: pnpm run scrape
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.MY_EMAIL }}
        git config --local user.name "Github Actions"
        git add .
        git commit -m "chore: update scrape data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}